# Generated by Django 6.0.3 on 2026-03-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('excerpt', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('published', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
