# Generated by Django 6.0.3 on 2026-03-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('us', 'US'), ('politics', 'Politics'), ('business', 'Business'), ('technology', 'Technology'), ('science', 'Science'), ('health', 'Health'), ('sports', 'Sports'), ('entertainment', 'Entertainment')], default='world', max_length=20),
        ),
    ]
