# Generated by Django 6.0.3 on 2026-03-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_story_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('us', 'US'), ('politics', 'Politics'), ('business', 'Business'), ('technology', 'Technology'), ('science', 'Science'), ('health', 'Health'), ('sports', 'Sports')], default='world', max_length=20),
        ),
    ]
