# Generated by Django 6.0.3 on 2026-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_story_language_alter_story_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title_fingerprint',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='story',
            name='url_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['language', 'published'], name='news_story_languag_7901c6_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['source', 'language'], name='news_story_source_d2be23_idx'),
        ),
    ]
