# Generated by Django 6.0.3 on 2026-03-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_story_title_fingerprint_story_url_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
