# Generated by Django 6.0.3 on 2026-03-27 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_story_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=5)),
                ('source_count', models.IntegerField(default=0)),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('representative_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representing_clusters', to='news.story')),
                ('stories', models.ManyToManyField(related_name='clusters', to='news.story')),
            ],
            options={
                'ordering': ['-source_count'],
            },
        ),
    ]
