# Generated by Django 6.0.3 on 2026-04-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_story_tweeted'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
