# Generated by Django 6.0.3 on 2026-05-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_story_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('share', 'Share'), ('feed_access', 'Feed Access'), ('widget_load', 'Widget Load')], db_index=True, max_length=20)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('language', models.CharField(blank=True, db_index=True, max_length=5)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=5)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='news_analyt_event_t_18936e_idx'), models.Index(fields=['country_code', 'timestamp'], name='news_analyt_country_c8e57e_idx')],
            },
        ),
    ]
