# Generated by Django 6.0.3 on 2026-05-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_analyticsevent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['language', 'published', 'source'], name='news_story_languag_8ad071_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['language', 'published', 'category'], name='news_story_languag_c890e0_idx'),
        ),
    ]
