# Generated by Django 6.0.3 on 2026-05-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_story_news_story_languag_8ad071_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('asin', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('world', 'World'), ('us', 'US'), ('politics', 'Politics'), ('business', 'Business'), ('technology', 'Technology'), ('science', 'Science'), ('health', 'Health'), ('sports', 'Sports'), ('entertainment', 'Entertainment')], max_length=20)),
                ('language', models.CharField(default='en', max_length=5)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', '-created_at'],
                'indexes': [models.Index(fields=['category', 'language', 'is_active'], name='news_recomm_categor_8156a2_idx')],
            },
        ),
    ]
