# Generated by Django 6.0.3 on 2026-05-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_recommendedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
