# Generated by Django 6.0.3 on 2026-05-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_analyticsevent_is_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('headline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list, help_text='Keywords for matching stories by title')),
                ('categories', models.JSONField(default=list, help_text="Categories to match (e.g., ['sports', 'world'])")),
                ('languages', models.JSONField(default=list, help_text='Language codes to include')),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(default=0, help_text='Sort order on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='news_topic_is_acti_8bef7b_idx')],
            },
        ),
    ]
