# Generated by Django 6.0.3 on 2026-05-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='translations',
            field=models.JSONField(default=dict, help_text="Translations by language: {'es': {'headline': '...', 'description': '...'}, ...}"),
        ),
    ]
