# Generated by Django 6.0.3 on 2026-05-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_topic_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='merchandise',
            field=models.JSONField(default=dict, help_text="Merchandise links: {'title': '...', 'items': [{'name': '...', 'url': '...', 'image': '...'}]}"),
        ),
    ]
