# Generated by Django 6.0.3 on 2026-05-28 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_topic_merchandise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('pt', 'Português'), ('it', 'Italiano'), ('ar', 'العربية'), ('ru', 'Русский'), ('ja', '日本語'), ('zh', '中文'), ('ko', '한국어'), ('tr', 'Türkçe'), ('hi', 'हिन्दी')], db_index=True, default='en', max_length=5)),
                ('question', models.CharField(max_length=300)),
                ('options', models.JSONField(default=list, help_text='List of option strings')),
                ('poll_type', models.CharField(choices=[('topical', 'Topical'), ('fun', 'Fun'), ('lifestyle', 'Lifestyle'), ('opinion', 'Opinion'), ('sports', 'Sports'), ('culture', 'Culture')], db_index=True, default='topical', max_length=20)),
                ('english_translation', models.CharField(blank=True, help_text='For review of non-English polls', max_length=300)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending_review', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('results', models.JSONField(default=dict, help_text='{option_index: count}')),
                ('source', models.CharField(default='auto', help_text='auto or manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'language'], name='news_poll_status_50e19d_idx'), models.Index(fields=['is_active', 'language', 'ends_at'], name='news_poll_is_acti_b8df09_idx'), models.Index(fields=['poll_type', 'created_at'], name='news_poll_poll_ty_9f74b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_index', models.IntegerField()),
                ('vote_hash', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='news.poll')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['poll', 'vote_hash'], name='news_pollvo_poll_id_99743a_idx')],
            },
        ),
    ]
