# Generated by Django 6.0.3 on 2026-05-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_poll_pollvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('share', 'Share'), ('feed_access', 'Feed Access'), ('widget_load', 'Widget Load'), ('poll_view', 'Poll View'), ('poll_vote', 'Poll Vote')], db_index=True, max_length=20),
        ),
    ]
