# Generated by Django 6.0.3 on 2026-05-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_analyticsevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollGenerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_hours', models.PositiveIntegerField(default=24, help_text='Hours between automatic poll generation runs')),
                ('polls_per_language', models.PositiveIntegerField(default=3, help_text='Polls to generate per language per run')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether automatic generation is enabled')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poll Generation Config',
                'verbose_name_plural': 'Poll Generation Configs',
            },
        ),
    ]
