# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_category(apps, schema_editor):
    Story = apps.get_model('news', 'Story')
    StoryCategory = apps.get_model('news', 'StoryCategory')
    links = []
    for story in Story.objects.exclude(category='').iterator(chunk_size=500):
        if story.category:
            links.append(StoryCategory(story_id=story.id, slug=story.category))
        if len(links) >= 500:
            StoryCategory.objects.bulk_create(links, ignore_conflicts=True)
            links = []
    if links:
        StoryCategory.objects.bulk_create(links, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_pollgenerationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=32)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='news.story')),
            ],
        ),
        migrations.AddConstraint(
            model_name='storycategory',
            constraint=models.UniqueConstraint(fields=('story', 'slug'), name='news_storycategory_story_slug_uniq'),
        ),
        migrations.RunPython(copy_legacy_category, noop_reverse),
    ]
