# Generated by Django 6.0.3 on 2026-09-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_pollvote_poll_vote_hash_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('pt', 'Português'), ('it', 'Italiano'), ('ar', 'العربية'), ('ru', 'Русский'), ('ja', '日本語'), ('zh', '中文'), ('ko', '한국어'), ('tr', 'Türkçe'), ('hi', 'हिन्दी')], default='en', max_length=5),
        ),
    ]
