# News sources configuration by language
from collections import OrderedDict

PAYWALLED_SOURCES = {
    # English
    'New York Post',
    'Bloomberg',
    'National Review',
    'The Atlantic',
    'Economist',
    'Financial Times',
    'Wall Street Journal',
    'New York Times',
    'Washington Post',
    'The New Yorker',
    # Spanish
    'El País',
    'El Mundo',
    'Expansión',
    'Cinco Días',
    'El Mercurio CL',
    'Clarín',
    'La Nación AR',
}

ENGLISH_FEEDS = [
    ('Reuters', 'https://news.google.com/rss/search?q=site:reuters.com&hl=en-US&gl=US&ceid=US:en'),
    ('AP', 'https://news.google.com/rss/search?q=site:apnews.com&hl=en-US&gl=US&ceid=US:en'),
    ('BBC', 'https://feeds.bbci.co.uk/news/rss.xml'),
    ('CBS News', 'https://news.google.com/rss/search?q=site:cbsnews.com&hl=en-US&gl=US&ceid=US:en'),
    ('ABC News', 'https://news.google.com/rss/search?q=site:abcnews.com&hl=en-US&gl=US&ceid=US:en'),
    ('NBC News', 'https://news.google.com/rss/search?q=site:nbcnews.com&hl=en-US&gl=US&ceid=US:en'),
    ('Sky News', 'https://news.google.com/rss/search?q=site:news.sky.com&hl=en-US&gl=US&ceid=US:en'),
    ('CNN', 'https://news.google.com/rss/search?q=site:cnn.com&hl=en-US&gl=US&ceid=US:en'),
    ('Bloomberg', 'https://news.google.com/rss/search?q=site:bloomberg.com&hl=en-US&gl=US&ceid=US:en'),
    ('Forbes', 'https://news.google.com/rss/search?q=site:forbes.com&hl=en-US&gl=US&ceid=US:en'),
    ('Yahoo News', 'https://news.google.com/rss/search?q=site:news.yahoo.com&hl=en-US&gl=US&ceid=US:en'),
    ('Newsweek', 'https://news.google.com/rss/search?q=site:newsweek.com&hl=en-US&gl=US&ceid=US:en'),
    ('Time', 'https://news.google.com/rss/search?q=site:time.com&hl=en-US&gl=US&ceid=US:en'),
    ('Free Press', 'https://www.thefp.com/feed'),
    ('NPR', 'https://feeds.npr.org/1001/rss.xml'),
    ('France 24', 'https://www.france24.com/en/rss'),
    ('Deutsche Welle', 'https://rss.dw.com/xml/rss-en-all'),
    ('Al Jazeera', 'https://www.aljazeera.com/xml/rss/all.xml'),
    ('New York Post', 'https://nypost.com/feed/'),
    ('Washington Examiner', 'https://www.washingtonexaminer.com/feed'),
    ('Daily Caller', 'https://dailycaller.com/feed/'),
    ('The Federalist', 'https://thefederalist.com/feed/'),
    ('National Review', 'https://www.nationalreview.com/feed/'),
    ('Daily Wire', 'https://news.google.com/rss/search?q=site:dailywire.com&hl=en-US&gl=US&ceid=US:en'),
    ('Epoch Times', 'https://news.google.com/rss/search?q=site:theepochtimes.com&hl=en-US&gl=US&ceid=US:en'),
    ('Townhall', 'https://townhall.com/feed'),
    ('RedState', 'https://redstate.com/feed/'),
    ('Mother Jones', 'https://www.motherjones.com/feed/'),
    ('HuffPost', 'https://news.google.com/rss/search?q=site:huffpost.com&hl=en-US&gl=US&ceid=US:en'),
    ('The Nation', 'https://news.google.com/rss/search?q=site:thenation.com&hl=en-US&gl=US&ceid=US:en'),
    ('Salon', 'https://www.salon.com/feed'),
    ('Jacobin', 'https://jacobin.com/feed'),
    ('The Intercept', 'https://theintercept.com/feed/'),
    ('Democracy Now', 'https://news.google.com/rss/search?q=site:democracynow.org&hl=en-US&gl=US&ceid=US:en'),
    ('Common Dreams', 'https://www.commondreams.org/rss.xml'),
    ('Truthout', 'https://truthout.org/rss.xml'),
    ('Vox', 'https://news.google.com/rss/search?q=site:vox.com&hl=en-US&gl=US&ceid=US:en'),
]

SPANISH_FEEDS = [
    # International Spanish news
    ('BBC Mundo', 'https://news.google.com/rss/search?q=site:bbc.com/mundo&hl=es&gl=ES&ceid=ES:es'),
    ('Deutsche Welle ES', 'https://rss.dw.com/xml/rss-es-all'),
    ('France 24 ES', 'https://www.france24.com/es/rss'),
    ('RT Español', 'https://news.google.com/rss/search?q=site:actualidad.rt.com&hl=es&gl=ES&ceid=ES:es'),
    ('CNN Español', 'https://news.google.com/rss/search?q=site:cnnespanol.cnn.com&hl=es&gl=ES&ceid=ES:es'),
    ('Euronews ES', 'https://es.euronews.com/rss'),
    
    # Spanish news agencies
    ('EFE', 'https://news.google.com/rss/search?q=site:efe.com&hl=es&gl=ES&ceid=ES:es'),
    
    # Major Spanish newspapers
    ('El País', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada'),
    ('El Mundo', 'https://estaticos.elmundo.es/elmundo/rss/portada.xml'),
    ('ABC ES', 'https://www.abc.es/rss/feeds/abc_Espana.xml'),
    ('La Vanguardia', 'https://www.lavanguardia.com/rss/home.xml'),
    ('El Confidencial', 'https://www.elconfidencial.com/rss/'),
    ('El Diario', 'https://www.eldiario.es/rss/'),
    ('Público', 'https://www.publico.es/rss/'),
    ('20 Minutos', 'https://www.20minutos.es/rss/'),
    
    # Latin American sources
    ('Clarín', 'https://www.clarin.com/rss/'),
    ('La Nación AR', 'https://www.lanacion.com.ar/arcio/rss/'),
    ('El Universal MX', 'https://www.eluniversal.com.mx/rss.xml'),
    ('El Comercio PE', 'https://www.elcomercio.pe/rss/'),
    ('El Tiempo CO', 'https://www.eltiempo.com/rss/opinion.xml'),
    ('El Mercurio CL', 'https://www.emol.com/rss/'),
    
    # Business
    ('Expansión', 'https://www.expansion.com/rss/portada.html'),
    ('Cinco Días', 'https://cincodias.elpais.com/cincodias/rss/portada.xml'),
    
    # Sports
    ('Marca', 'https://e00-marca.uecdn.es/rss/portada.xml'),
    ('AS', 'https://feeds.as.com/rss/section/26h00t000p1.xml'),
    ('Sport ES', 'https://www.sport.es/es/rss/portada/rss.xml'),
]

LANGUAGE_FEEDS = {
    'en': ENGLISH_FEEDS,
    'es': SPANISH_FEEDS,
}

LANGUAGE_SOURCE_INFO = {
    'en': {
        'Reuters': ('Center', '#666', 'https://mediabiasfactcheck.com/reuters/'),
        'AP': ('Center', '#666', 'https://mediabiasfactcheck.com/associated-press/'),
        'BBC': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/bbc/'),
        'NPR': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/npr/'),
        'France 24': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/france-24/'),
        'Deutsche Welle': ('Center', '#666', 'https://mediabiasfactcheck.com/deutsche-welle/'),
        'Al Jazeera': ('Left', '#999', 'https://mediabiasfactcheck.com/al-jazeera/'),
        'CBS News': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/cbs-news/'),
        'ABC News': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/abc-news/'),
        'NBC News': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/nbc-news/'),
        'Fox News': ('Right', '#666', 'https://mediabiasfactcheck.com/fox-news/'),
        'CNN': ('Left', '#999', 'https://mediabiasfactcheck.com/cnn/'),
        'Sky News': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/sky-news/'),
        'Bloomberg': ('Center', '#666', 'https://mediabiasfactcheck.com/bloomberg/'),
        'Forbes': ('Center', '#666', 'https://mediabiasfactcheck.com/forbes/'),
        'Yahoo News': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/yahoo-news/'),
        'Newsweek': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/newsweek/'),
        'Time': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/time/'),
        'Free Press': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'New York Post': ('Right', '#666', 'https://mediabiasfactcheck.com/new-york-post/'),
        'Washington Examiner': ('Right-Center', '#777', 'https://mediabiasfactcheck.com/washington-examiner/'),
        'Daily Caller': ('Right', '#666', 'https://mediabiasfactcheck.com/daily-caller/'),
        'The Federalist': ('Right', '#666', 'https://mediabiasfactcheck.com/the-federalist/'),
        'National Review': ('Right', '#666', 'https://mediabiasfactcheck.com/national-review/'),
        'Daily Wire': ('Right', '#666', 'https://mediabiasfactcheck.com/daily-wire/'),
        'Epoch Times': ('Right', '#666', 'https://mediabiasfactcheck.com/epoch-times/'),
        'Townhall': ('Right', '#666', 'https://mediabiasfactcheck.com/townhall/'),
        'RedState': ('Right', '#666', 'https://mediabiasfactcheck.com/redstate/'),
        'Mother Jones': ('Left', '#999', 'https://mediabiasfactcheck.com/mother-jones/'),
        'HuffPost': ('Left', '#999', 'https://mediabiasfactcheck.com/huffington-post/'),
        'The Nation': ('Left', '#999', 'https://mediabiasfactcheck.com/the-nation/'),
        'Salon': ('Left', '#999', 'https://mediabiasfactcheck.com/salon/'),
        'Jacobin': ('Left', '#999', 'https://mediabiasfactcheck.com/jacobin/'),
        'The Intercept': ('Left', '#999', 'https://mediabiasfactcheck.com/the-intercept/'),
        'Democracy Now': ('Left', '#999', 'https://mediabiasfactcheck.com/democracy-now/'),
        'Common Dreams': ('Left', '#999', 'https://mediabiasfactcheck.com/common-dreams/'),
        'Truthout': ('Left', '#999', 'https://mediabiasfactcheck.com/truthout/'),
        'Vox': ('Left', '#999', 'https://mediabiasfactcheck.com/vox/'),
    },
    'es': {
        'BBC Mundo': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/bbc/'),
        'Deutsche Welle ES': ('Center', '#666', 'https://mediabiasfactcheck.com/deutsche-welle/'),
        'France 24 ES': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/france-24/'),
        'RT Español': ('Right', '#666', 'https://mediabiasfactcheck.com/rt/'),
        'CNN Español': ('Left', '#999', 'https://mediabiasfactcheck.com/cnn/'),
        'Euronews ES': ('Center', '#666', 'https://mediabiasfactcheck.com/euronews/'),
        'EFE': ('Center', '#666', 'https://mediabiasfactcheck.com/efe/'),
        'El País': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/el-pais/'),
        'El Mundo': ('Center', '#666', 'https://mediabiasfactcheck.com/el-mundo/'),
        'ABC ES': ('Right-Center', '#777', 'https://mediabiasfactcheck.com/abc-spain/'),
        'La Vanguardia': ('Center', '#666', 'https://mediabiasfactcheck.com/la-vanguardia/'),
        'El Confidencial': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'El Diario': ('Left', '#999', 'https://mediabiasfactcheck.com/'),
        'Público': ('Left', '#999', 'https://mediabiasfactcheck.com/'),
        '20 Minutos': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'Clarín': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'La Nación AR': ('Right-Center', '#777', 'https://mediabiasfactcheck.com/'),
        'El Universal MX': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'El Comercio PE': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'El Tiempo CO': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'El Mercurio CL': ('Right-Center', '#777', 'https://mediabiasfactcheck.com/'),
        'Expansión': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'Cinco Días': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'Marca': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'AS': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'Sport ES': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
    }
}

DEFAULT_SOURCES = {
    'en': ['Reuters', 'AP', 'Deutsche Welle', 'Bloomberg', 'Forbes', 'Free Press'],
    'es': ['BBC Mundo', 'Deutsche Welle ES', 'France 24 ES', 'EFE', 'El País', 'Clarín'],
}

SOURCES = {
    'en': [
        ('Reuters', 'Center'),
        ('AP', 'Center'),
        ('Deutsche Welle', 'Center'),
        ('Bloomberg', 'Center'),
        ('Forbes', 'Center'),
        ('Free Press', 'Center'),
        ('BBC', 'Left-Center'),
        ('CBS News', 'Left-Center'),
        ('ABC News', 'Left-Center'),
        ('NBC News', 'Left-Center'),
        ('Sky News', 'Left-Center'),
        ('NPR', 'Left-Center'),
        ('France 24', 'Left-Center'),
        ('Yahoo News', 'Left-Center'),
        ('Newsweek', 'Left-Center'),
        ('Time', 'Left-Center'),
        ('CNN', 'Left'),
        ('Al Jazeera', 'Left'),
        ('Mother Jones', 'Left'),
        ('HuffPost', 'Left'),
        ('The Nation', 'Left'),
        ('Salon', 'Left'),
        ('Jacobin', 'Left'),
        ('The Intercept', 'Left'),
        ('Democracy Now', 'Left'),
        ('Common Dreams', 'Left'),
        ('Truthout', 'Left'),
        ('Vox', 'Left'),
        ('Washington Examiner', 'Right-Center'),
        ('Townhall', 'Right'),
        ('New York Post', 'Right'),
        ('Daily Caller', 'Right'),
        ('RedState', 'Right'),
        ('The Federalist', 'Right'),
        ('National Review', 'Right'),
        ('Daily Wire', 'Right'),
        ('Epoch Times', 'Right'),
        ('Fox News', 'Right'),
    ],
    'es': [
        ('EFE', 'Center'),
        ('Deutsche Welle ES', 'Center'),
        ('Euronews ES', 'Center'),
        ('El Mundo', 'Center'),
        ('La Vanguardia', 'Center'),
        ('El Confidencial', 'Center'),
        ('20 Minutos', 'Center'),
        ('Clarín', 'Center'),
        ('El Universal MX', 'Center'),
        ('El Comercio PE', 'Center'),
        ('El Tiempo CO', 'Center'),
        ('Expansión', 'Center'),
        ('Cinco Días', 'Center'),
        ('Marca', 'Center'),
        ('AS', 'Center'),
        ('Sport ES', 'Center'),
        ('BBC Mundo', 'Left-Center'),
        ('France 24 ES', 'Left-Center'),
        ('El País', 'Left-Center'),
        ('La Nación AR', 'Right-Center'),
        ('ABC ES', 'Right-Center'),
        ('El Mercurio CL', 'Right-Center'),
        ('CNN Español', 'Left'),
        ('El Diario', 'Left'),
        ('Público', 'Left'),
        ('RT Español', 'Right'),
    ],
}

LANGUAGE_STOP_WORDS = {
    'en': {
        'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
        'of', 'with', 'by', 'from', 'is', 'are', 'was', 'were', 'be', 'been',
        'has', 'have', 'had', 'do', 'does', 'did', 'will', 'would', 'could',
        'should', 'may', 'might', 'can', 'shall', 'not', 'no', 'its', 'it',
        'as', 'that', 'this', 'these', 'those', 'he', 'she', 'they', 'we',
        'him', 'her', 'them', 'their', 'our', 'my', 'your', 'his', 'i',
        'up', 'out', 'about', 'into', 'over', 'after', 'before', 'between',
        'under', 'above', 'so', 'than', 'too', 'very', 'just', 'also', 'more',
        'new', 'says', 'said', 'say',
    },
    'es': {
        'el', 'la', 'los', 'las', 'un', 'una', 'unos', 'unas', 'y', 'o', 'pero',
        'en', 'de', 'del', 'al', 'a', 'para', 'por', 'con', 'sin', 'sobre',
        'es', 'son', 'era', 'eran', 'fue', 'ser', 'estar', 'está', 'están',
        'ha', 'he', 'han', 'hay', 'haber', 'que', 'cual', 'quien', 'como',
        'este', 'esta', 'estos', 'estas', 'ese', 'esa', 'esos', 'esas',
        'él', 'ella', 'ellos', 'ellas', 'su', 'sus', 'mi', 'tu', 'nos',
        'yo', 'me', 'te', 'se', 'lo', 'le', 'les', 'nos', 'más', 'muy',
        'ya', 'no', 'si', 'sí', 'ni', 'también', 'así', 'entre', 'hasta',
        'desde', 'cuando', 'donde', 'todo', 'cada', 'otro', 'otra', 'otros',
        'nuevo', 'nueva', 'nuevos', 'nuevas', 'dice', 'dijo', 'según',
    },
}

LANGUAGE_NAMES = {
    'en': 'English',
    'es': 'Español',
}

CATEGORY_KEYWORDS = {
    'en': {
        'politics': [
            'trump', 'biden', 'congress', 'senate', 'election', 'vote', 'voting', 'campaign',
            'republican', 'democrat', 'president', 'administration', 'governor', 'lawmaker',
            'legislation', 'democratic', 'political', 'parliament', 'impeach', 'supreme court',
            'ruling', 'policy', 'white house', 'cabinet', 'secretary', 'convention', 'primary',
            'ballot', 'midterm', 'senator', 'representative', 'gop', 'dnc', 'rnc', 'capitol',
            'partisan', 'bipartisan', 'filibuster', 'veto', 'executive order', 'federal',
        ],
        'business': [
            'stock market', 'economy', 'economic', 'trade', 'tariff', 'inflation', 'federal reserve',
            'gdp', 'recession', 'unemployment', 'jobs report', 'earnings', 'revenue', 'profit',
            'bank', 'finance', 'financial', 'investment', 'wall street', 'ceo', 'opec', 'crypto',
            'bitcoin', 'bond', 'investor', 'shares', 'commodity', 'crude oil', 'dow jones',
            'nasdaq', 's&p', 'ipo', 'merger', 'acquisition', 'quarterly', 'fiscal',
            'interest rate', 'treasury', 'market', 'business', 'corporate', 'startup',
        ],
        'technology': [
            'tech', 'ai ', 'artificial intelligence', 'software', 'startup', 'silicon valley',
            'cyberattack', 'hacker', 'data breach', 'digital', 'robot', 'elon musk', 'iphone',
            'android', 'chip', 'semiconductor', 'cloud computing', 'openai', 'nvidia', 'meta ',
            'google ', 'microsoft', 'apple ', 'amazon ', 'facebook', 'twitter', 'x ', 'tesla',
            'cybersecurity', 'blockchain', 'cryptocurrency', 'app ', 'algorithm', 'machine learning',
            'deep learning', 'chatgpt', 'neural', 'quantum computing', '5g', 'iot',
        ],
        'science': [
            'nasa', 'spacex', 'space', 'mars', 'climate change', 'earthquake', 'volcano',
            'researcher', 'laboratory', 'experiment', 'discovery', 'species', 'genetic',
            'cosmos', 'astronomy', 'physics', 'chemistry', 'biology', 'geology', 'ocean',
            'arctic', 'antarctic', 'fossil', 'dinosaur', 'evolution', 'ecosystem', 'biodiversity',
            'telescope', 'satellite', 'rocket', 'asteroid', 'comet', 'solar', 'lunar',
            'planet', 'galaxy', 'universe', 'quantum', 'molecule', 'atom', 'nuclear',
        ],
        'health': [
            'hospital', 'doctor', 'medical', 'medicine', 'drug', 'fda ', 'vaccine', 'pandemic',
            'cancer', 'diabetes', 'heart disease', 'brain ', 'treatment', 'therapy', 'surgery',
            'patient', 'outbreak', 'virus', 'covid', 'epidemic', 'healthcare', 'clinic', 'nurse',
            'physician', 'mental health', 'depression', 'anxiety', 'stroke', 'symptom', 'diagnosis',
            'clinical trial', 'pharmaceutical', 'opioid', 'obesity', 'nutrition', 'fitness',
            'exercise', 'sleep', 'stress', 'immunity', 'infection', 'antibiotic', 'chronic',
            'acute', 'emergency', 'pediatric', 'geriatric', 'oncology', 'cardiology',
        ],
        'sports': [
            'nba', 'nfl', 'mlb', 'nhl', 'championship', 'playoffs', 'super bowl', 'world cup',
            'olympics', 'marathon', 'tennis', 'golf', 'soccer', 'basketball', 'baseball',
            'football', 'coach', 'injury', 'tournament', 'athlete', 'score', 'draft', 'trade',
            'fifa', 'uefa', 'premier league', 'la liga', 'serie a', ' bundesliga', 'ligue 1',
            'champions league', 'world series', 'grand slam', 'wimbledon', 'masters',
            'quarterback', 'pitcher', 'striker', 'midfielder', 'goalkeeper', 'referee',
            'stadium', 'arena', 'league', 'division', 'conference', 'wild card', 'mvp',
            'all-star', 'rookie', 'veteran', 'retirement', 'contract', 'free agent',
        ],
        'us': [
            'california', 'texas', 'florida', 'new york', 'washington', 'chicago', 'los angeles',
            'miami', 'seattle', 'boston', 'atlanta', 'houston', 'dallas', 'phoenix', 'denver',
            'detroit', 'portland', 'philadelphia', 'san francisco', 'san diego', 'austin',
            'nashville', 'memphis', 'las vegas', 'sacramento', 'orlando', 'tampa', 'raleigh',
            'pittsburgh', 'cleveland', 'cincinnati', 'milwaukee', 'minneapolis', 'indianapolis',
            'columbus', 'charlotte', 'kansas city', 'st. louis', 'new orleans', 'baltimore',
            'maryland', 'virginia', 'nevada', 'arizona', 'georgia', 'north carolina',
            'pennsylvania', 'ohio', 'michigan', 'illinois', 'new jersey', 'massachusetts',
            'connecticut', 'colorado', 'oregon', 'washington state', 'idaho', 'utah',
            'alabama', 'south carolina', 'tennessee', 'kentucky', 'indiana', 'wisconsin',
            'iowa', 'nebraska', 'kansas', 'oklahoma', 'missouri', 'arkansas', 'louisiana',
            'mississippi', 'alaska', 'hawaii', 'fbi', 'cia', 'pentagon', 'capitol hill',
            'american', 'americans', 'u.s.', 'united states', 'america', 'midwest', 'south',
            'northeast', 'west coast', 'east coast', 'gulf', 'great lakes',
        ],
        'world': [
            'ukraine', 'russia', 'china', 'iran', 'israel', 'gaza', 'middle east', 'europe',
            'asia', 'africa', 'latin america', 'european union', 'nato', 'war', 'ceasefire',
            'diplomat', 'summit', 'border', 'immigration', 'refugee', 'global', 'international',
            'united nations', 'un ', 'who ', 'brexit', 'sanctions', 'embassy', 'foreign',
            'treaty', 'alliance', 'conflict', 'military', 'army', 'navy', 'air force',
            'missile', 'nuclear', 'weapon', 'terror', 'extremist', 'rebel', 'insurgent',
            'peacekeeping', 'humanitarian', 'crisis', 'disaster', 'famine', 'drought',
            'flood', 'hurricane', 'typhoon', 'earthquake', 'tsunami', 'volcano',
        ],
        'entertainment': [
            'movie', 'film', 'actor', 'actress', 'oscar', 'grammy', 'emmy', 'celebrity',
            'music', 'album', 'concert', 'tour', 'netflix', 'streaming', 'box office',
            'broadway', 'theater', 'tv show', 'series', 'season premiere', 'finale',
            'rapper', 'singer', 'band', 'album release', 'billboard', 'spotify',
            'disney', 'marvel', 'star wars', 'hollywood', 'award show', 'red carpet',
            'reality tv', 'sitcom', 'drama', 'comedy', 'horror', 'thriller',
            'video game', 'gaming', 'esports', 'twitch', 'youtube', 'tiktok',
            'influencer', 'viral', 'streamer', 'podcast', 'bestseller', 'book release',
        ],
    },
    'es': {
        'politics': [
            'elecciones', 'gobierno', 'presidente', 'congreso', 'senado', 'voto', 'campaña',
            'partido', 'política', 'ministro', 'ley', 'diputado', 'alcalde', 'gobernador',
            'elección', 'parlamento', 'constitución', 'reforma', 'oposición',
        ],
        'business': [
            'bolsa', 'economía', 'mercado', 'empresa', 'negocio', 'banco', 'finanzas',
            'inversión', 'dólar', 'peso', ' euro ', 'inflación', 'desempleo', 'pib',
            'acciones', 'divisa', 'crédito', 'deuda', 'exportación', 'importación',
        ],
        'technology': [
            'tecnología', 'inteligencia artificial', 'software', 'ciberataque', 'digital',
            'robot', 'aplicación', 'smartphone', 'internet', 'computación', 'datos',
            'ciberseguridad', 'algoritmo', 'plataforma', 'redes sociales',
        ],
        'science': [
            'ciencia', 'investigación', 'descubrimiento', 'especie', 'genético', 'clima',
            'terremoto', 'volcán', 'planeta', 'espacio', 'universo', 'física', 'química',
            'biología', 'laboratorio', 'estudio', 'científico', 'nasa', 'astronáutica',
        ],
        'health': [
            'hospital', 'médico', 'medicina', 'vacuna', 'pandemia', 'salud', 'enfermedad',
            'tratamiento', 'virus', 'clínica', 'paciente', 'cirugía', 'terapia', 'síntoma',
            'diagnóstico', 'farmacéutico', 'nutrición', 'ejercicio', 'bienestar', 'covid',
        ],
        'sports': [
            'fútbol', 'liga', 'champions', 'copa', 'mundial', 'olimpiadas', 'deporte',
            'equipo', 'jugador', 'partido', 'gol', 'tenis', 'baloncesto', 'béisbol',
            'entrenador', 'estadio', 'torneo', 'campeonato', 'selección', 'árbitro',
            'clásico', 'derby', 'ascenso', 'descenso', 'tabla', 'posiciones',
        ],
        'us': [
            'estados unidos', 'ee.uu.', 'norteamérica', 'florida', 'texas', 'california',
            'nueva york', 'miami', 'los ángeles', 'chicago', 'washington',
        ],
        'world': [
            'ucrania', 'rusia', 'china', 'irán', 'israel', 'gaza', 'medio oriente', 'europa',
            'asia', 'áfrica', 'américa latina', 'guerra', 'diplomático', 'inmigración',
            'refugiado', 'mundial', 'internacional', 'onu', 'otan', 'conflicto', 'crisis',
            'militar', 'ejército', 'paz', 'acuerdo', 'tratado', 'sanciones',
        ],
        'entertainment': [
            'película', 'cine', 'actor', 'actriz', 'oscar', 'grammy', 'celebridad',
            'música', 'álbum', 'concierto', 'gira', 'netflix', 'streaming', 'taquilla',
            'teatro', 'serie', 'temporada', 'final de temporada',
            'cantante', 'banda', 'billboard', 'spotify',
            'disney', 'hollywood', 'premio', 'alfombra roja',
            'reality', 'comedia', 'drama', 'terror',
            'videojuego', 'gaming', 'esports', 'twitch', 'youtube', 'tiktok',
            'influencer', 'viral', 'podcast', 'bestseller', 'libro',
            'televisión', 'tele', 'programa', 'famoso', 'famosa',
        ],
    },
}

CATEGORY_NAMES = {
    'en': OrderedDict([
        ('all', 'All'),
        ('most_covered', 'Most Covered'),
        ('world', 'World'),
        ('us', 'US'),
        ('politics', 'Politics'),
        ('business', 'Business'),
        ('technology', 'Technology'),
        ('science', 'Science'),
        ('health', 'Health'),
        ('sports', 'Sports'),
        ('entertainment', 'Entertainment'),
    ]),
    'es': OrderedDict([
        ('all', 'Todo'),
        ('most_covered', 'Más Cubierto'),
        ('world', 'Mundo'),
        ('us', 'EE.UU.'),
        ('politics', 'Política'),
        ('business', 'Negocios'),
        ('technology', 'Tecnología'),
        ('science', 'Ciencia'),
        ('health', 'Salud'),
        ('sports', 'Deportes'),
        ('entertainment', 'Entretenimiento'),
    ]),
}

SOURCE_ATTRIBUTION = {
    'en': r'\s*(Reuters|AP News|AP|BBC|CBS|ABC|NBC|CNN|Bloomberg|Forbes|NPR|Al Jazeera|Deutsche Welle|France 24|Sky News|Yahoo|Newsweek|Time|Free Press)\s*$',
    'es': r'\s*(BBC Mundo|Deutsche Welle|France 24|CNN|Euronews|EFE|El País|El Mundo|ABC|Clarín|La Nación|Reuters|AP)\s*$',
}

GENERIC_TEXT = {
    'en': ['comprehensive up-to-date news coverage', 'aggregated from', 'click here for more'],
    'es': ['cobertura de noticias actualizada', 'agregado desde', 'haga clic aquí'],
}

UI_STRINGS = {
    'en': {
        'subtitle': 'Choose your bias | Wire services and other feeds | Last 24 hours',
        'how_it_works': 'How it works',
        'privacy_text': 'We respect your privacy. This site uses contextual ads (no tracking cookies) and shows headlines/summaries under fair use.',
        'privacy_link': 'Privacy Policy',
        'got_it': 'Got it',
        'sources': 'Sources:',
        'center_default': 'Center sources (default)',
        'all_sources': 'All sources',
        'center_only': 'Center only',
        'left_center_only': 'Left-Center only',
        'left_only': 'Left only',
        'right_only': 'Right only',
        'clear_all': 'Clear all',
        'sources_suffix': 'sources',
        'covered_by_2': 'Stories covered by 2 or more sources',
        'paywall_title': 'Paywalled site',
        'sources_label': 'sources',
        'read_full': 'Read full story',
        'find_coverage': 'Find coverage',
        'search_related': 'Search for related coverage',
        'bias_rating': 'Bias rating',
        'ago': 'ago',
        'show_stories': 'Show',
        'stories': 'stories',
        'no_stories': 'No stories in this category',
        'footer_copy': 'News content &copy; respective publishers. Headlines and summaries used under fair use for informational purposes.',
        'footer_sources': 'Sources:',
        'footer_and': 'and',
        'footer_terms': 'Terms',
        'footer_privacy': 'Privacy',
        'footer_about': 'About',
    },
    'es': {
        'subtitle': 'Elige tu sesgo | Servicios de cables y otros feeds | Últimas 24 horas',
        'how_it_works': 'Cómo funciona',
        'privacy_text': 'Respetamos tu privacidad. Este sitio usa anuncios contextuales (sin cookies de rastreo) y muestra titulares/resúmenes bajo uso justo.',
        'privacy_link': 'Política de privacidad',
        'got_it': 'Entendido',
        'sources': 'Fuentes:',
        'center_default': 'Fuentes centrales (predeterminado)',
        'all_sources': 'Todas las fuentes',
        'center_only': 'Solo centro',
        'left_center_only': 'Solo centro-izquierda',
        'left_only': 'Solo izquierda',
        'right_only': 'Solo derecha',
        'clear_all': 'Borrar todo',
        'sources_suffix': 'fuentes',
        'covered_by_2': 'Historias cubiertas por 2 o más fuentes',
        'paywall_title': 'Sitio con muro de pago',
        'sources_label': 'fuentes',
        'read_full': 'Leer historia completa',
        'find_coverage': 'Encontrar cobertura',
        'search_related': 'Buscar cobertura relacionada',
        'bias_rating': 'Calificación de sesgo',
        'ago': 'ago',
        'show_stories': 'Mostrar',
        'stories': 'historias',
        'no_stories': 'No hay historias en esta categoría',
        'footer_copy': 'Contenido de noticias © respectivos editores. Titulares y resúmenes utilizados bajo uso justo con fines informativos.',
        'footer_sources': 'Fuentes:',
        'footer_and': 'y',
        'footer_terms': 'Términos',
        'footer_privacy': 'Privacidad',
        'footer_about': 'Acerca de',
    },
}
