# News sources configuration by language

PAYWALLED_SOURCES = {
    # English
    'New York Post',
    'Bloomberg',
    'National Review',
    'The Atlantic',
    'Economist',
    'Financial Times',
    'Wall Street Journal',
    'New York Times',
    'Washington Post',
    'The New Yorker',
    # Spanish
    'El País',
    'El Mundo',
    'Expansión',
    'Cinco Días',
    'El Mercurio CL',
    'Clarín',
    'La Nación AR',
}

ENGLISH_FEEDS = [
    ('Reuters', 'https://news.google.com/rss/search?q=site:reuters.com&hl=en-US&gl=US&ceid=US:en'),
    ('AP', 'https://news.google.com/rss/search?q=site:apnews.com&hl=en-US&gl=US&ceid=US:en'),
    ('BBC', 'https://feeds.bbci.co.uk/news/rss.xml'),
    ('CBS News', 'https://news.google.com/rss/search?q=site:cbsnews.com&hl=en-US&gl=US&ceid=US:en'),
    ('ABC News', 'https://news.google.com/rss/search?q=site:abcnews.com&hl=en-US&gl=US&ceid=US:en'),
    ('NBC News', 'https://news.google.com/rss/search?q=site:nbcnews.com&hl=en-US&gl=US&ceid=US:en'),
    ('Sky News', 'https://news.google.com/rss/search?q=site:news.sky.com&hl=en-US&gl=US&ceid=US:en'),
    ('CNN', 'https://news.google.com/rss/search?q=site:cnn.com&hl=en-US&gl=US&ceid=US:en'),
    ('Bloomberg', 'https://news.google.com/rss/search?q=site:bloomberg.com&hl=en-US&gl=US&ceid=US:en'),
    ('Forbes', 'https://news.google.com/rss/search?q=site:forbes.com&hl=en-US&gl=US&ceid=US:en'),
    ('Yahoo News', 'https://news.google.com/rss/search?q=site:news.yahoo.com&hl=en-US&gl=US&ceid=US:en'),
    ('Newsweek', 'https://news.google.com/rss/search?q=site:newsweek.com&hl=en-US&gl=US&ceid=US:en'),
    ('Time', 'https://news.google.com/rss/search?q=site:time.com&hl=en-US&gl=US&ceid=US:en'),
    ('Free Press', 'https://www.thefp.com/feed'),
    ('NPR', 'https://feeds.npr.org/1001/rss.xml'),
    ('France 24', 'https://www.france24.com/en/rss'),
    ('Deutsche Welle', 'https://rss.dw.com/xml/rss-en-all'),
    ('Al Jazeera', 'https://www.aljazeera.com/xml/rss/all.xml'),
    ('New York Post', 'https://nypost.com/feed/'),
    ('Washington Examiner', 'https://www.washingtonexaminer.com/feed'),
    ('Daily Caller', 'https://dailycaller.com/feed/'),
    ('The Federalist', 'https://thefederalist.com/feed/'),
    ('National Review', 'https://www.nationalreview.com/feed/'),
    ('Daily Wire', 'https://news.google.com/rss/search?q=site:dailywire.com&hl=en-US&gl=US&ceid=US:en'),
    ('Epoch Times', 'https://news.google.com/rss/search?q=site:theepochtimes.com&hl=en-US&gl=US&ceid=US:en'),
    ('Townhall', 'https://townhall.com/feed'),
    ('RedState', 'https://redstate.com/feed/'),
    ('Mother Jones', 'https://www.motherjones.com/feed/'),
    ('HuffPost', 'https://news.google.com/rss/search?q=site:huffpost.com&hl=en-US&gl=US&ceid=US:en'),
    ('The Nation', 'https://news.google.com/rss/search?q=site:thenation.com&hl=en-US&gl=US&ceid=US:en'),
    ('Salon', 'https://www.salon.com/feed'),
    ('Jacobin', 'https://jacobin.com/feed'),
    ('The Intercept', 'https://theintercept.com/feed/'),
    ('Democracy Now', 'https://news.google.com/rss/search?q=site:democracynow.org&hl=en-US&gl=US&ceid=US:en'),
    ('Common Dreams', 'https://www.commondreams.org/rss.xml'),
    ('Truthout', 'https://truthout.org/rss.xml'),
    ('Vox', 'https://news.google.com/rss/search?q=site:vox.com&hl=en-US&gl=US&ceid=US:en'),
]

SPANISH_FEEDS = [
    # International Spanish news
    ('BBC Mundo', 'https://news.google.com/rss/search?q=site:bbc.com/mundo&hl=es&gl=ES&ceid=ES:es'),
    ('Deutsche Welle ES', 'https://rss.dw.com/xml/rss-es-all'),
    ('France 24 ES', 'https://www.france24.com/es/rss'),
    ('RT Español', 'https://news.google.com/rss/search?q=site:actualidad.rt.com&hl=es&gl=ES&ceid=ES:es'),
    ('CNN Español', 'https://news.google.com/rss/search?q=site:cnnespanol.cnn.com&hl=es&gl=ES&ceid=ES:es'),
    ('Euronews ES', 'https://es.euronews.com/rss'),
    
    # Spanish news agencies
    ('EFE', 'https://news.google.com/rss/search?q=site:efe.com&hl=es&gl=ES&ceid=ES:es'),
    
    # Major Spanish newspapers
    ('El País', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada'),
    ('El Mundo', 'https://estaticos.elmundo.es/elmundo/rss/portada.xml'),
    ('ABC ES', 'https://www.abc.es/rss/feeds/abc_Espana.xml'),
    ('La Vanguardia', 'https://www.lavanguardia.com/rss/home.xml'),
    ('El Confidencial', 'https://www.elconfidencial.com/rss/'),
    ('El Diario', 'https://www.eldiario.es/rss/'),
    ('Público', 'https://www.publico.es/rss/'),
    ('20 Minutos', 'https://www.20minutos.es/rss/'),
    
    # Latin American sources
    ('Clarín', 'https://www.clarin.com/rss/'),
    ('La Nación AR', 'https://www.lanacion.com.ar/arcio/rss/'),
    ('El Universal MX', 'https://www.eluniversal.com.mx/rss.xml'),
    ('El Comercio PE', 'https://www.elcomercio.pe/rss/'),
    ('El Tiempo CO', 'https://www.eltiempo.com/rss/opinion.xml'),
    ('El Mercurio CL', 'https://www.emol.com/rss/'),
    
    # Business
    ('Expansión', 'https://www.expansion.com/rss/portada.html'),
    ('Cinco Días', 'https://cincodias.elpais.com/cincodias/rss/portada.xml'),
    
    # Sports
    ('Marca', 'https://e00-marca.uecdn.es/rss/portada.xml'),
    ('AS', 'https://feeds.as.com/rss/section/26h00t000p1.xml'),
    ('Sport ES', 'https://www.sport.es/es/rss/portada/rss.xml'),
]

LANGUAGE_FEEDS = {
    'en': ENGLISH_FEEDS,
    'es': SPANISH_FEEDS,
}

LANGUAGE_SOURCE_INFO = {
    'en': {
        'Reuters': ('Center', '#666', 'https://mediabiasfactcheck.com/reuters/'),
        'AP': ('Center', '#666', 'https://mediabiasfactcheck.com/associated-press/'),
        'BBC': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/bbc/'),
        'NPR': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/npr/'),
        'France 24': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/france-24/'),
        'Deutsche Welle': ('Center', '#666', 'https://mediabiasfactcheck.com/deutsche-welle/'),
        'Al Jazeera': ('Left', '#999', 'https://mediabiasfactcheck.com/al-jazeera/'),
        'CBS News': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/cbs-news/'),
        'ABC News': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/abc-news/'),
        'NBC News': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/nbc-news/'),
        'Fox News': ('Right', '#666', 'https://mediabiasfactcheck.com/fox-news/'),
        'CNN': ('Left', '#999', 'https://mediabiasfactcheck.com/cnn/'),
        'Sky News': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/sky-news/'),
        'Bloomberg': ('Center', '#666', 'https://mediabiasfactcheck.com/bloomberg/'),
        'Forbes': ('Center', '#666', 'https://mediabiasfactcheck.com/forbes/'),
        'Yahoo News': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/yahoo-news/'),
        'Newsweek': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/newsweek/'),
        'Time': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/time/'),
        'Free Press': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'New York Post': ('Right', '#666', 'https://mediabiasfactcheck.com/new-york-post/'),
        'Washington Examiner': ('Right-Center', '#777', 'https://mediabiasfactcheck.com/washington-examiner/'),
        'Daily Caller': ('Right', '#666', 'https://mediabiasfactcheck.com/daily-caller/'),
        'The Federalist': ('Right', '#666', 'https://mediabiasfactcheck.com/the-federalist/'),
        'National Review': ('Right', '#666', 'https://mediabiasfactcheck.com/national-review/'),
        'Daily Wire': ('Right', '#666', 'https://mediabiasfactcheck.com/daily-wire/'),
        'Epoch Times': ('Right', '#666', 'https://mediabiasfactcheck.com/epoch-times/'),
        'Townhall': ('Right', '#666', 'https://mediabiasfactcheck.com/townhall/'),
        'RedState': ('Right', '#666', 'https://mediabiasfactcheck.com/redstate/'),
        'Mother Jones': ('Left', '#999', 'https://mediabiasfactcheck.com/mother-jones/'),
        'HuffPost': ('Left', '#999', 'https://mediabiasfactcheck.com/huffington-post/'),
        'The Nation': ('Left', '#999', 'https://mediabiasfactcheck.com/the-nation/'),
        'Salon': ('Left', '#999', 'https://mediabiasfactcheck.com/salon/'),
        'Jacobin': ('Left', '#999', 'https://mediabiasfactcheck.com/jacobin/'),
        'The Intercept': ('Left', '#999', 'https://mediabiasfactcheck.com/the-intercept/'),
        'Democracy Now': ('Left', '#999', 'https://mediabiasfactcheck.com/democracy-now/'),
        'Common Dreams': ('Left', '#999', 'https://mediabiasfactcheck.com/common-dreams/'),
        'Truthout': ('Left', '#999', 'https://mediabiasfactcheck.com/truthout/'),
        'Vox': ('Left', '#999', 'https://mediabiasfactcheck.com/vox/'),
    },
    'es': {
        'BBC Mundo': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/bbc/'),
        'Deutsche Welle ES': ('Center', '#666', 'https://mediabiasfactcheck.com/deutsche-welle/'),
        'France 24 ES': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/france-24/'),
        'RT Español': ('Right', '#666', 'https://mediabiasfactcheck.com/rt/'),
        'CNN Español': ('Left', '#999', 'https://mediabiasfactcheck.com/cnn/'),
        'Euronews ES': ('Center', '#666', 'https://mediabiasfactcheck.com/euronews/'),
        'EFE': ('Center', '#666', 'https://mediabiasfactcheck.com/efe/'),
        'El País': ('Left-Center', '#888', 'https://mediabiasfactcheck.com/el-pais/'),
        'El Mundo': ('Center', '#666', 'https://mediabiasfactcheck.com/el-mundo/'),
        'ABC ES': ('Right-Center', '#777', 'https://mediabiasfactcheck.com/abc-spain/'),
        'La Vanguardia': ('Center', '#666', 'https://mediabiasfactcheck.com/la-vanguardia/'),
        'El Confidencial': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'El Diario': ('Left', '#999', 'https://mediabiasfactcheck.com/'),
        'Público': ('Left', '#999', 'https://mediabiasfactcheck.com/'),
        '20 Minutos': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'Clarín': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'La Nación AR': ('Right-Center', '#777', 'https://mediabiasfactcheck.com/'),
        'El Universal MX': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'El Comercio PE': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'El Tiempo CO': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'El Mercurio CL': ('Right-Center', '#777', 'https://mediabiasfactcheck.com/'),
        'Expansión': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'Cinco Días': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'Marca': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'AS': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
        'Sport ES': ('Center', '#666', 'https://mediabiasfactcheck.com/'),
    }
}

DEFAULT_SOURCES = {
    'en': ['Reuters', 'AP', 'Deutsche Welle', 'Bloomberg', 'Forbes', 'Free Press'],
    'es': ['BBC Mundo', 'Deutsche Welle ES', 'France 24 ES', 'EFE', 'El País', 'Clarín'],
}

SOURCES = {
    'en': [
        ('Reuters', 'Center'),
        ('AP', 'Center'),
        ('Deutsche Welle', 'Center'),
        ('Bloomberg', 'Center'),
        ('Forbes', 'Center'),
        ('Free Press', 'Center'),
        ('BBC', 'Left-Center'),
        ('CBS News', 'Left-Center'),
        ('ABC News', 'Left-Center'),
        ('NBC News', 'Left-Center'),
        ('Sky News', 'Left-Center'),
        ('NPR', 'Left-Center'),
        ('France 24', 'Left-Center'),
        ('Yahoo News', 'Left-Center'),
        ('Newsweek', 'Left-Center'),
        ('Time', 'Left-Center'),
        ('CNN', 'Left'),
        ('Al Jazeera', 'Left'),
        ('Mother Jones', 'Left'),
        ('HuffPost', 'Left'),
        ('The Nation', 'Left'),
        ('Salon', 'Left'),
        ('Jacobin', 'Left'),
        ('The Intercept', 'Left'),
        ('Democracy Now', 'Left'),
        ('Common Dreams', 'Left'),
        ('Truthout', 'Left'),
        ('Vox', 'Left'),
        ('Washington Examiner', 'Right-Center'),
        ('Townhall', 'Right'),
        ('New York Post', 'Right'),
        ('Daily Caller', 'Right'),
        ('RedState', 'Right'),
        ('The Federalist', 'Right'),
        ('National Review', 'Right'),
        ('Daily Wire', 'Right'),
        ('Epoch Times', 'Right'),
        ('Fox News', 'Right'),
    ],
    'es': [
        ('EFE', 'Center'),
        ('Deutsche Welle ES', 'Center'),
        ('Euronews ES', 'Center'),
        ('El Mundo', 'Center'),
        ('La Vanguardia', 'Center'),
        ('El Confidencial', 'Center'),
        ('20 Minutos', 'Center'),
        ('Clarín', 'Center'),
        ('El Universal MX', 'Center'),
        ('El Comercio PE', 'Center'),
        ('El Tiempo CO', 'Center'),
        ('Expansión', 'Center'),
        ('Cinco Días', 'Center'),
        ('Marca', 'Center'),
        ('AS', 'Center'),
        ('Sport ES', 'Center'),
        ('BBC Mundo', 'Left-Center'),
        ('France 24 ES', 'Left-Center'),
        ('El País', 'Left-Center'),
        ('La Nación AR', 'Right-Center'),
        ('ABC ES', 'Right-Center'),
        ('El Mercurio CL', 'Right-Center'),
        ('CNN Español', 'Left'),
        ('El Diario', 'Left'),
        ('Público', 'Left'),
        ('RT Español', 'Right'),
    ],
}

LANGUAGE_NAMES = {
    'en': 'English',
    'es': 'Español',
}
